/**
 *
 * $Id$
 */
package videowatermarking.validation;

import org.eclipse.emf.common.util.EList;
import videowatermarking.Video;

/**
 * A sample validator interface for {@link videowatermarking.User}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UserValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateId(int value);

	boolean validateFrameNo(int value);

	boolean validateVideo(EList<Video> value);

}
