/**
 *
 * $Id$
 */
package videowatermarking.validation;

import org.eclipse.emf.common.util.EList;

import videowatermarking.Database;
import videowatermarking.Filter;
import videowatermarking.User;
import videowatermarking.Video;

/**
 * A sample validator interface for {@link videowatermarking.VideoWatermark}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VideoWatermarkValidator {
	boolean validate();

	boolean validateDatabase(EList<Database> value);

	boolean validateFilter(EList<Filter> value);

	boolean validateUser(EList<User> value);

	boolean validateVideo(EList<Video> value);
}
