/**
 *
 * $Id$
 */
package videowatermarking.validation;

import org.eclipse.emf.common.util.EList;
import videowatermarking.Database;
import videowatermarking.GeneticAlgorithm;

/**
 * A sample validator interface for {@link videowatermarking.Video}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VideoValidator {
	boolean validate();

	boolean validateVideoName(String value);

	boolean validateVideoType(String value);

	boolean validateGeneticalgorithm(EList<GeneticAlgorithm> value);

	boolean validateDatabase(EList<Database> value);
}
